# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MusicSplitter(object):
    def setupUi(self, MusicSplitter):
        MusicSplitter.setObjectName(_fromUtf8("MusicSplitter"))
        MusicSplitter.resize(500, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MusicSplitter.sizePolicy().hasHeightForWidth())
        MusicSplitter.setSizePolicy(sizePolicy)
        MusicSplitter.setMinimumSize(QtCore.QSize(450, 500))
        self.centralWidget = QtGui.QWidget(MusicSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.chosenFile = QtGui.QLabel(self.centralWidget)
        self.chosenFile.setText(_fromUtf8(""))
        self.chosenFile.setObjectName(_fromUtf8("chosenFile"))
        self.horizontalLayout_2.addWidget(self.chosenFile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lengthBox = QtGui.QDoubleSpinBox(self.centralWidget)
        self.lengthBox.setSingleStep(0.5)
        self.lengthBox.setProperty("value", 3.0)
        self.lengthBox.setObjectName(_fromUtf8("lengthBox"))
        self.gridLayout_2.addWidget(self.lengthBox, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 2, 1, 1)
        self.bandStartBox = QtGui.QSpinBox(self.centralWidget)
        self.bandStartBox.setMinimum(40)
        self.bandStartBox.setMaximum(20000)
        self.bandStartBox.setObjectName(_fromUtf8("bandStartBox"))
        self.gridLayout_2.addWidget(self.bandStartBox, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.bandEndBox = QtGui.QSpinBox(self.centralWidget)
        self.bandEndBox.setMinimum(40)
        self.bandEndBox.setMaximum(20000)
        self.bandEndBox.setProperty("value", 2000)
        self.bandEndBox.setObjectName(_fromUtf8("bandEndBox"))
        self.gridLayout_2.addWidget(self.bandEndBox, 1, 3, 1, 1)
        self.songLenBox = QtGui.QSpinBox(self.centralWidget)
        self.songLenBox.setMinimum(1)
        self.songLenBox.setMaximum(1000)
        self.songLenBox.setProperty("value", 120)
        self.songLenBox.setObjectName(_fromUtf8("songLenBox"))
        self.gridLayout_2.addWidget(self.songLenBox, 2, 1, 1, 1)
        self.levelBox = QtGui.QDoubleSpinBox(self.centralWidget)
        self.levelBox.setMaximum(1.0)
        self.levelBox.setSingleStep(0.1)
        self.levelBox.setProperty("value", 0.45)
        self.levelBox.setObjectName(_fromUtf8("levelBox"))
        self.gridLayout_2.addWidget(self.levelBox, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        self.mediancheckBox = QtGui.QCheckBox(self.centralWidget)
        self.mediancheckBox.setText(_fromUtf8(""))
        self.mediancheckBox.setChecked(True)
        self.mediancheckBox.setObjectName(_fromUtf8("mediancheckBox"))
        self.gridLayout_2.addWidget(self.mediancheckBox, 2, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.coresNumBox = QtGui.QSpinBox(self.centralWidget)
        self.coresNumBox.setMinimum(1)
        self.coresNumBox.setMaximum(8)
        self.coresNumBox.setProperty("value", 1)
        self.coresNumBox.setObjectName(_fromUtf8("coresNumBox"))
        self.gridLayout_2.addWidget(self.coresNumBox, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.browseButton = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton.sizePolicy().hasHeightForWidth())
        self.browseButton.setSizePolicy(sizePolicy)
        self.browseButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.verticalLayout_2.addWidget(self.browseButton)
        self.processButton = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processButton.sizePolicy().hasHeightForWidth())
        self.processButton.setSizePolicy(sizePolicy)
        self.processButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.processButton.setObjectName(_fromUtf8("processButton"))
        self.verticalLayout_2.addWidget(self.processButton)
        self.tableView = QtGui.QTableView(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout_2.addWidget(self.tableView)
        self.saveButton = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.verticalLayout_2.addWidget(self.saveButton)
        MusicSplitter.setCentralWidget(self.centralWidget)

        self.retranslateUi(MusicSplitter)
        QtCore.QMetaObject.connectSlotsByName(MusicSplitter)

    def retranslateUi(self, MusicSplitter):
        MusicSplitter.setWindowTitle(_translate("MusicSplitter", "MainWindow", None))
        self.label_4.setText(_translate("MusicSplitter", "File:", None))
        self.label_2.setText(_translate("MusicSplitter", "Silence length [s]", None))
        self.label_6.setText(_translate("MusicSplitter", "Min. song length [s]", None))
        self.label_7.setText(_translate("MusicSplitter", "Median filter", None))
        self.label.setText(_translate("MusicSplitter", "Silence level", None))
        self.label_5.setText(_translate("MusicSplitter", "Band start [Hz]", None))
        self.label_3.setText(_translate("MusicSplitter", "Band end [Hz]", None))
        self.label_8.setText(_translate("MusicSplitter", "Number of cores", None))
        self.browseButton.setText(_translate("MusicSplitter", "Browse file", None))
        self.processButton.setText(_translate("MusicSplitter", "Process file", None))
        self.saveButton.setText(_translate("MusicSplitter", "Save all", None))

