# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MUL/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MusicSplitter(object):
    def setupUi(self, MusicSplitter):
        MusicSplitter.setObjectName(_fromUtf8("MusicSplitter"))
        MusicSplitter.resize(450, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MusicSplitter.sizePolicy().hasHeightForWidth())
        MusicSplitter.setSizePolicy(sizePolicy)
        MusicSplitter.setMinimumSize(QtCore.QSize(450, 500))
        self.centralWidget = QtGui.QWidget(MusicSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.chosenFile = QtGui.QLabel(self.centralWidget)
        self.chosenFile.setText(_fromUtf8(""))
        self.chosenFile.setObjectName(_fromUtf8("chosenFile"))
        self.horizontalLayout_2.addWidget(self.chosenFile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.levelBox = QtGui.QDoubleSpinBox(self.centralWidget)
        self.levelBox.setMaximum(1.0)
        self.levelBox.setSingleStep(0.1)
        self.levelBox.setObjectName(_fromUtf8("levelBox"))
        self.horizontalLayout.addWidget(self.levelBox)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lengthBox = QtGui.QDoubleSpinBox(self.centralWidget)
        self.lengthBox.setObjectName(_fromUtf8("lengthBox"))
        self.horizontalLayout.addWidget(self.lengthBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.bandStartBox = QtGui.QSpinBox(self.centralWidget)
        self.bandStartBox.setMinimum(40)
        self.bandStartBox.setMaximum(20000)
        self.bandStartBox.setObjectName(_fromUtf8("bandStartBox"))
        self.horizontalLayout_3.addWidget(self.bandStartBox)
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.bandEndBox = QtGui.QSpinBox(self.centralWidget)
        self.bandEndBox.setMinimum(40)
        self.bandEndBox.setMaximum(20000)
        self.bandEndBox.setObjectName(_fromUtf8("bandEndBox"))
        self.horizontalLayout_3.addWidget(self.bandEndBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.songLenBox = QtGui.QSpinBox(self.centralWidget)
        self.songLenBox.setMaximum(1000)
        self.songLenBox.setObjectName(_fromUtf8("songLenBox"))
        self.horizontalLayout_4.addWidget(self.songLenBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.browseButton = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton.sizePolicy().hasHeightForWidth())
        self.browseButton.setSizePolicy(sizePolicy)
        self.browseButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.verticalLayout_2.addWidget(self.browseButton)
        self.processButton = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processButton.sizePolicy().hasHeightForWidth())
        self.processButton.setSizePolicy(sizePolicy)
        self.processButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.processButton.setObjectName(_fromUtf8("processButton"))
        self.verticalLayout_2.addWidget(self.processButton)
        self.tableView = QtGui.QTableView(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout_2.addWidget(self.tableView)
        MusicSplitter.setCentralWidget(self.centralWidget)

        self.retranslateUi(MusicSplitter)
        QtCore.QMetaObject.connectSlotsByName(MusicSplitter)

    def retranslateUi(self, MusicSplitter):
        MusicSplitter.setWindowTitle(_translate("MusicSplitter", "MainWindow", None))
        self.label_4.setText(_translate("MusicSplitter", "File:", None))
        self.label.setText(_translate("MusicSplitter", "Silence level", None))
        self.label_2.setText(_translate("MusicSplitter", "Silence length [s]", None))
        self.label_5.setText(_translate("MusicSplitter", "Band start [Hz]", None))
        self.label_3.setText(_translate("MusicSplitter", "Band end [Hz]", None))
        self.label_6.setText(_translate("MusicSplitter", "Min. song length [s]", None))
        self.browseButton.setText(_translate("MusicSplitter", "Browse file ...", None))
        self.processButton.setText(_translate("MusicSplitter", "Process audio", None))

